### ISSUE TITLE
Home link on navbar of the blog

### ISSUE THREAD

**Issue by unkemptArc99** [KamandPrompt/kamandprompt.github.io#62]
With reference to #53 , good work adding the navbar on the blog. But I would also like a Home link on the navbar, because it is better in terms of user readability, and how easily user can navigate on our page. Currently it is on the left hand side of the website, and is bound to be missed by the user. Hence, add a home link on the navbar.

**Comment by rishi-s8** [comment]
It was there initially. @Shrikha1, did you remove it?

**Comment by Shrikha1** [comment]
We have About tab in the navbar of the blog which links to the website.

**Comment by abhigyank** [comment]
@unkemptArc99  Do you mean a link on the blog webpage that leads to the KamandPrompt website?

**Comment by unkemptArc99** [comment]
Yes. Currently it is on the left hand side of the page. I would like it to be moved near the "About" link. That way it is more intuitive to the user.

**Comment by abhigyank** [comment]
@unkemptArc99 Though I get your point, I am not really sure it'd be a good idea. Consider this scenerio 0 
You're reading a blog post and you want to go the home page for the list of blogs. Now intuitively you'd click home, but instead of taking you to the home page of the blog it takes you to the original KP website. I don't feel this is a correct UX. I'd feel the blog to be not so directly connected with the main website. Your thoughts?

**Comment by abhigyank** [comment]
Yeah, regarding the website on the left sidebar I agree with you. We already have the facebook and github links on the footer so we could simply remove them from the left sidebar. I'll create an issue for that.

Regarding a "Home" link on the navbar, I understand your viewpoint on it and want to have a link to however I just feel that we could name it better instead of "Home". Do you have any ideas ? Also we could include a link in the footer to the website instead. What do you think?

**Comment by abhigyank** [comment]
@rishi-s8  @Shrikha1  Is this possible to do - 
* Replace "KamandPrompt Blog" on the top left corner with the logo and redirect to the main KP website. 
* Add a blog heading before about to redirect to `/blog`.
@unkemptArc99  What do you think about this solution?

**Comment by unkemptArc99** [comment]
Yeah that would work as well

**Comment by abhigyank** [comment]
Completed in https://github.com/KamandPrompt/blog/pull/8
