### ISSUE TITLE
SEO Tags

### ISSUE THREAD

**Issue by abhigyank** [KamandPrompt/kamandprompt.github.io#82]
Add Seo tags for search engine discovery.

**Comment by pranshukharkwal** [comment]
@abhigyank 
What all work has to be done in terms of SEO. 
Here is what all I propose : 

1) Edit meta description for the homepage, by adding more content and keywords
2) Add meta tags for other pages, which do not have them currently
3) Adding the site to Google Webmaster tools
4) Creating a sitemap and adding it to the search console.

What else has to be done? Because currently, the page doesn't even rank on top for "Programming club of IIT Mandi" , "IIT Mandi Programming Club" keywords and I think we should make efforts to achieve that.

**Comment by abhigyank** [comment]
> Edit meta description for the homepage, by adding more content and keywords

Definitely, sounds good. Though Google doesn't give much importance to keywords now, as people have used it to _game_ search queries. But other meta tags should definitey help.
> Add meta tags for other pages, which do not have them currently

Yes, I think having the same basic meta description and content in all pages would help.

>Adding the site to Google Webmaster tools

This would definitely be good. But this is probably that maybe @vsvipul or @dheeraj135 would look at.

>Creating a sitemap and adding it to the search console

Yup, sitemap would also help search engine bots index the website better, leading to having most pages in search results.

We should definitely try to get the page in top results on search engine. One thing I think that might help is having the title as "KamandPrompt | Programming Club IIT Mandi", this might help get is in top rank when one searches for "Programming club of IIT Mandi". We are on top when one searches for KamandPrompt, so this might help.

**Comment by dheeraj135** [comment]
I will take care of this issue.

**Comment by pranshukharkwal** [comment]
@abhigyank  you can take a look at #114 , and then maybe we can close this issue

**Comment by abhigyank** [comment]
Good work @pranshukharkwal
